# Generated by Django 3.2 on 2021-04-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0003_ckkimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckkimage',
            name='position',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
