# Generated by Django 3.2 on 2021-04-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0002_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CKKImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(default=1, unique=True)),
                ('fname', models.CharField(default='placeholder.jpg', max_length=100)),
                ('local', models.ImageField(upload_to='images/')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ckk.ckkitem')),
            ],
        ),
    ]
