# Generated by Django 3.2 on 2021-05-07 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ckk', '0004_alter_ckkimage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ckkimage',
            name='fname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ckkimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ckk.ckkitem'),
        ),
    ]
